@startuml
title 基于GitHub的实验管理平台--老师选择班级用例的顺序图
actor users
users-->Term:操作系统需要先选择学期
Term-->Subject:选择学期之后也需要选择课程
Subject -> Teacher
Teacher-->test
test-->class 
class-->Teacher:返回老师在该学期\n该课程该实验的班级

@enduml